[package]
name = "better_dexp"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.2", package = "gtk4" }
ureq = "2.2.0"
serde_json = "1.0.67"